# Generated by Django 5.1.2 on 2024-10-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jobmodel_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='Bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Viewer_Profile_Pic'),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Viewer_Profile_Pic'),
        ),
    ]
