# Generated by Django 5.1.2 on 2024-10-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_recruiterprofilemodel_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='recruiterprofilemodel',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='Profile_Pic',
        ),
    ]
