# Generated by Django 5.1.2 on 2024-10-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_recruiterprofilemodel_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterprofilemodel',
            old_name='skills',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('hardware', 'Hardware')], max_length=100, null=True),
        ),
    ]
